In [21]:
 
import numpy as np 
import pandas as pd
import seaborn as sns 

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer

dataset=pd.read_csv('C:\\Users\\BCA 11\\Downloads\\Data.csv')
print(dataset,"Dataset \n")

#Extracting independent variable: 
x=dataset.iloc[:,:-1].values
print(x," x value \n")

#extracting dependent variable: 
y=dataset.iloc[:,3].values
print(y," y value\n")

#Dealing with Missing Data: 
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:])
x[:,1:]=imputer.transform(x[:,1:])
print(x,"\n")

#handling of categorical data

labelencoder_X=LabelEncoder()
x[:,0]=labelencoder_X.fit_transform(x[:,0])
rg=ColumnTransformer([("Region",OneHotEncoder(),[0])],remainder='passthrough')
x=rg.fit_transform(x)
labelencoder_Y=LabelEncoder()
y=labelencoder_Y.fit_transform(y)
print(x,"\n")
print(y,"\n")

   Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes 

[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 nan]
 ['India' 40.0 69600.0]
 ['Brazil' nan 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]] 

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[['India' 49.0 86400.0]
 ['Brazil' 32.0 57600.0]
 ['USA' 35.0 64800.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 76533.33333333333]
 ['India' 40.0 69600.0]
 ['Brazil' 43.77777777777778 62400.0]
 ['India' 53.0 94800.0]
 ['USA' 55.0 99600.0]
 ['India' 42.0 80400.0]]
[[0.0

In [19]:
import numpy as np 
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

dataset=pd.read_csv('C:\\Users\\BCA 11\\Downloads\\Data.csv')
print(dataset,"\n")
labelencoder_X = LabelEncoder()
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,3].values
X[:, 0] = labelencoder_X.fit_transform(X[:, 0]) 
rg = ColumnTransformer([("Region", OneHotEncoder(), [0])], remainder =
'passthrough')
X = rg.fit_transform(X)
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y) 
print(X)
print(Y)

   Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes
5   India  40.0  69600.0            Yes
6  Brazil   NaN  62400.0             No
7   India  53.0  94800.0            Yes
8     USA  55.0  99600.0             No
9   India  42.0  80400.0            Yes 

[[0.0 1.0 0.0 49.0 86400.0]
 [1.0 0.0 0.0 32.0 57600.0]
 [0.0 0.0 1.0 35.0 64800.0]
 [1.0 0.0 0.0 43.0 73200.0]
 [0.0 0.0 1.0 45.0 nan]
 [0.0 1.0 0.0 40.0 69600.0]
 [1.0 0.0 0.0 nan 62400.0]
 [0.0 1.0 0.0 53.0 94800.0]
 [0.0 0.0 1.0 55.0 99600.0]
 [0.0 1.0 0.0 42.0 80400.0]]
[0 1 0 0 1 1 0 1 0 1]


In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

dataset=pd.read_csv("C:\\r lang programs\\preprocessing\\PlayTennis.csv")
print(dataset)
y=dataset.Play
x=dataset.drop('Play',axis=1)
print(y,"\n")
print(x,"\n")
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train,"\n")
print(x_test,"\n")


     Outlook Temperature Humidity    Wind Play
0      Sunny         Hot     High    Weak   No
1      Sunny         Hot     High  Strong   No
2   Overcast         Hot     High    Weak  Yes
3       Rain        Mild     High    Weak  Yes
4       Rain        Cool   Normal    Weak  Yes
5       Rain        Cool   Normal  Strong   No
6   Overcast        Cool   Normal  Strong  Yes
7      Sunny        Mild     High    Weak   No
8      Sunny        Cool   Normal    Weak  Yes
9       Rain        Mild   Normal    Weak  Yes
10     Sunny        Mild   Normal  Strong  Yes
11  Overcast        Mild     High  Strong  Yes
12  Overcast         Hot   Normal    Weak  Yes
13      Rain        Mild     High  Strong   No
0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play, dtype: object 

     Outlook Temperature Humidity    Wind
0      Sunny         Hot     High    Weak
1      Sunny         Hot     High  Strong
2

In [ ]:
import pandas S pd
import sklearn

